### ISSUE TITLE
Doesn't seem to work in Xcode 6/iOS 8

### ISSUE THREAD

**Issue by aaronbrethorst** [alexito4/AMPPreviewController#1]
![ios simulator screen shot aug 24 2014 11 47 50 am](https://cloud.githubusercontent.com/assets/2254/4024245/30f5b6fc-2bbf-11e4-9a2e-5c4126559573.png)

**Comment by markrickert** [comment]
> Fixed in GM Seed

Can be closed.

**Comment by alexito4** [comment]
Thanks ;)
